"""baseline

Revision ID: 87d3312bcd2b
Revises: 
Create Date: 2026-07-17 19:28:21.861092
"""
from alembic import op
import sqlalchemy as sa


revision = '87d3312bcd2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('room', 'rack', 'shelf', 'slot', 'server', 'other', name='locationtype'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('full_path', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_parent_id'), 'locations', ['parent_id'], unique=False)
    op.create_table('plugins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('entry', sa.String(length=200), nullable=False),
    sa.Column('table_schema', sa.JSON(), nullable=False),
    sa.Column('allowed_hosts', sa.JSON(), nullable=False),
    sa.Column('contributions', sa.JSON(), nullable=False),
    sa.Column('service_spec', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('all_users', sa.Boolean(), nullable=False),
    sa.Column('allowed_user_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('provider_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('price_input', sa.Float(), nullable=False),
    sa.Column('price_output', sa.Float(), nullable=False),
    sa.Column('price_cache_read', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'model', name='uq_provider_model')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_color', sa.String(length=20), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('global_role', sa.Enum('admin', 'user', name='globalrole'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'disabled', name='userstatus'), nullable=False),
    sa.Column('claude_oauth_token_enc', sa.String(), nullable=False),
    sa.Column('codex_token_enc', sa.String(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('max_runners', sa.Integer(), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_project_view', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('webhook_coalesce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=120), nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('window_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payloads', sa.JSON(), nullable=False),
    sa.Column('flushed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_coalesce_route'), 'webhook_coalesce', ['route'], unique=False)
    op.create_table('mcp_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('transport', sa.String(length=20), nullable=False),
    sa.Column('command', sa.String(length=500), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('env_enc', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('disabled_tools', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_mcp_server')
    )
    op.create_index(op.f('ix_mcp_servers_user_id'), 'mcp_servers', ['user_id'], unique=False)
    op.create_table('plugin_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', 'path', name='uq_plugin_file')
    )
    op.create_index(op.f('ix_plugin_files_plugin_id'), 'plugin_files', ['plugin_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('avatar_color', sa.String(length=20), nullable=False),
    sa.Column('lead_user_id', sa.Integer(), nullable=True),
    sa.Column('workspace_dir', sa.String(length=500), nullable=False),
    sa.Column('github_repo', sa.String(length=500), nullable=False),
    sa.Column('git_token_enc', sa.String(), nullable=False),
    sa.Column('git_enabled', sa.Boolean(), nullable=False),
    sa.Column('work_in_branches', sa.Boolean(), nullable=False),
    sa.Column('merge_target', sa.String(length=255), nullable=False),
    sa.Column('push_after_merge', sa.Boolean(), nullable=False),
    sa.Column('auto_pull', sa.Boolean(), nullable=False),
    sa.Column('pull_interval_min', sa.Integer(), nullable=False),
    sa.Column('managed', sa.Boolean(), nullable=False),
    sa.Column('auto_create_agents', sa.Boolean(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('pm_chat_enabled', sa.Boolean(), nullable=False),
    sa.Column('plan_agent', sa.String(length=100), nullable=False),
    sa.Column('exec_agent', sa.String(length=100), nullable=False),
    sa.Column('verify_command', sa.Text(), nullable=False),
    sa.Column('review_enabled', sa.Boolean(), nullable=False),
    sa.Column('review_agent', sa.String(length=100), nullable=False),
    sa.Column('auto_continue', sa.Boolean(), nullable=False),
    sa.Column('comment_triggers_agent', sa.Boolean(), nullable=False),
    sa.Column('auto_deploy', sa.Boolean(), nullable=False),
    sa.Column('screenshot_enabled', sa.Boolean(), nullable=False),
    sa.Column('vault_moc_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_projects_parent_id'), 'projects', ['parent_id'], unique=False)
    op.create_table('saved_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('query_json', sa.Text(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_filters_owner_id'), 'saved_filters', ['owner_id'], unique=False)
    op.create_table('user_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('value_enc', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_secret')
    )
    op.create_index(op.f('ix_user_secrets_user_id'), 'user_secrets', ['user_id'], unique=False)
    op.create_table('agent_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('fallback', sa.String(length=50), nullable=True),
    sa.Column('effort', sa.String(length=10), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('max_context_tokens', sa.Integer(), nullable=True),
    sa.Column('max_turns_planning', sa.Integer(), nullable=False),
    sa.Column('max_turns_execution', sa.Integer(), nullable=False),
    sa.Column('can_code', sa.Boolean(), nullable=False),
    sa.Column('can_read_code', sa.Boolean(), nullable=False),
    sa.Column('can_delegate', sa.Boolean(), nullable=False),
    sa.Column('web_search', sa.Boolean(), nullable=False),
    sa.Column('allowed_tools', sa.JSON(), nullable=False),
    sa.Column('allowed_skills', sa.JSON(), nullable=False),
    sa.Column('delegate_to', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_definitions_user_id'), 'agent_definitions', ['user_id'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('kanban', 'scrum', name='boardtype'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boards_project_id'), 'boards', ['project_id'], unique=False)
    op.create_table('hardware_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('issue_counters',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('issue_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('category', sa.Enum('standard', 'subtask', 'epic', 'hardware', name='issuetypecategory'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_types_project_id'), 'issue_types', ['project_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('schedule', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('command', sa.String(length=500), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('notify_mode', sa.String(length=20), nullable=False),
    sa.Column('notify_chat', sa.String(length=64), nullable=True),
    sa.Column('result_html', sa.Boolean(), nullable=False),
    sa.Column('pause_on_success', sa.Boolean(), nullable=False),
    sa.Column('run_timeout', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('author_label', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('meta_type', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_project_id'), 'messages', ['project_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=150), nullable=False),
    sa.Column('resource', sa.String(length=500), nullable=False),
    sa.Column('action', sa.Enum('allow', 'ask', 'deny', name='permaction'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_project_id'), 'permissions', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'maintainer', 'member', 'viewer', name='projectrole'), nullable=False),
    sa.Column('ai_assign', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('autostart', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_key'), 'skills', ['key'], unique=False)
    op.create_table('webhook_subs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=120), nullable=False),
    sa.Column('secret', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('status_new', sa.String(length=20), nullable=False),
    sa.Column('title_template', sa.String(length=500), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('silent', sa.Boolean(), nullable=False),
    sa.Column('event_header', sa.String(length=120), nullable=True),
    sa.Column('event_filter', sa.String(length=255), nullable=True),
    sa.Column('event_key_header', sa.String(length=120), nullable=True),
    sa.Column('event_cooldowns', sa.JSON(), nullable=False),
    sa.Column('alert_events', sa.JSON(), nullable=False),
    sa.Column('ref_field', sa.String(length=120), nullable=True),
    sa.Column('notify_chat', sa.String(length=64), nullable=True),
    sa.Column('permissions_json', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route')
    )
    op.create_table('workflow_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('todo', 'in_progress', 'done', name='statuscategory'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_statuses_project_id'), 'workflow_statuses', ['project_id'], unique=False)
    op.create_table('board_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['workflow_statuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'status_id', name='uq_board_column')
    )
    op.create_index(op.f('ix_board_columns_board_id'), 'board_columns', ['board_id'], unique=False)
    op.create_table('hardware_workflow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['hardware_workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hardware_workflow_steps_workflow_id'), 'hardware_workflow_steps', ['workflow_id'], unique=False)
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_job_id'), 'job_runs', ['job_id'], unique=False)
    op.create_table('sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('future', 'active', 'closed', name='sprintstate'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprints_board_id'), 'sprints', ['board_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('agent_status', sa.Enum('open', 'planning', 'plan_review', 'approved', 'in_progress', 'testing', 'to_test', 'done', 'hold', 'failed', name='ticketagentstatus'), nullable=True),
    sa.Column('hold_reason', sa.Enum('plan_review', 'plan_split', 'question', 'merge', 'verify', 'review', 'incomplete', 'stuck', 'cap', 'interrupted', 'permission', name='holdreason'), nullable=True),
    sa.Column('priority', sa.Enum('lowest', 'low', 'medium', 'high', 'highest', name='priority'), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_agent', sa.String(length=100), nullable=True),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(length=64), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('night_task', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('plan_agent', sa.String(length=100), nullable=True),
    sa.Column('exec_agent', sa.String(length=100), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('base_branch', sa.String(length=255), nullable=True),
    sa.Column('git_base_sha', sa.String(length=64), nullable=True),
    sa.Column('continuation_count', sa.Integer(), nullable=False),
    sa.Column('agent_working', sa.Boolean(), nullable=False),
    sa.Column('merge_status', sa.String(length=20), nullable=False),
    sa.Column('merge_commit', sa.String(length=64), nullable=True),
    sa.Column('merged_into', sa.String(length=255), nullable=True),
    sa.Column('merge_error', sa.Text(), nullable=True),
    sa.Column('parent_ticket_id', sa.Integer(), nullable=True),
    sa.Column('split_order', sa.Integer(), nullable=True),
    sa.Column('testenv_status', sa.String(length=20), nullable=False),
    sa.Column('testenv_url', sa.String(length=1000), nullable=True),
    sa.Column('testenv_container', sa.String(length=200), nullable=True),
    sa.Column('testenv_port', sa.Integer(), nullable=True),
    sa.Column('testenv_error', sa.Text(), nullable=True),
    sa.Column('testenv_env_enc', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_ticket_id'], ['issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['workflow_statuses.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['issue_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_issues_assignee_user_id'), 'issues', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_issues_project_id'), 'issues', ['project_id'], unique=False)
    op.create_index(op.f('ix_issues_sprint_id'), 'issues', ['sprint_id'], unique=False)
    op.create_index(op.f('ix_issues_status_id'), 'issues', ['status_id'], unique=False)
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_issue_id'), 'activity_log', ['issue_id'], unique=False)
    op.create_table('blockers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('asked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answered_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockers_issue_id'), 'blockers', ['issue_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_label', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_issue_id'), 'comments', ['issue_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('stack_dir', sa.String(length=500), nullable=False),
    sa.Column('worktree', sa.String(length=500), nullable=False),
    sa.Column('check_only', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hardware_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('purchase_status', sa.Enum('planned', 'ordered', 'delivered', 'installed', 'stored', 'retired', name='purchasestatus'), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('install_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warranty_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['hardware_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id')
    )
    op.create_index(op.f('ix_hardware_assets_location_id'), 'hardware_assets', ['location_id'], unique=False)
    op.create_index(op.f('ix_hardware_assets_model_id'), 'hardware_assets', ['model_id'], unique=False)
    op.create_index(op.f('ix_hardware_assets_project_id'), 'hardware_assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_hardware_assets_purchase_status'), 'hardware_assets', ['purchase_status'], unique=False)
    op.create_table('issue_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('blocks', 'relates', 'duplicates', 'clones', name='linktype'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'type', name='uq_issue_link')
    )
    op.create_table('issue_tags',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id', 'tag_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('perm_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=150), nullable=False),
    sa.Column('resource', sa.String(length=500), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perm_grants_issue_id'), 'perm_grants', ['issue_id'], unique=False)
    op.create_table('perm_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('tool', sa.String(length=150), nullable=False),
    sa.Column('resource', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perm_requests_issue_id'), 'perm_requests', ['issue_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(length=200), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('claude_sub_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('continuation_index', sa.Integer(), nullable=False),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('worktree_fingerprint', sa.String(length=100), nullable=True),
    sa.Column('last_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_issue_id'), 'runs', ['issue_id'], unique=False)
    op.create_table('cost_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_entries_project_id'), 'cost_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_cost_entries_run_id'), 'cost_entries', ['run_id'], unique=False)
    op.create_table('hardware_asset_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['hardware_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hardware_asset_steps_asset_id'), 'hardware_asset_steps', ['asset_id'], unique=False)
    op.create_table('run_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('tool_name', sa.String(length=150), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_steps_run_id'), 'run_steps', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_steps_run_id'), table_name='run_steps')
    op.drop_table('run_steps')
    op.drop_index(op.f('ix_hardware_asset_steps_asset_id'), table_name='hardware_asset_steps')
    op.drop_table('hardware_asset_steps')
    op.drop_index(op.f('ix_cost_entries_run_id'), table_name='cost_entries')
    op.drop_index(op.f('ix_cost_entries_project_id'), table_name='cost_entries')
    op.drop_table('cost_entries')
    op.drop_index(op.f('ix_runs_issue_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_perm_requests_issue_id'), table_name='perm_requests')
    op.drop_table('perm_requests')
    op.drop_index(op.f('ix_perm_grants_issue_id'), table_name='perm_grants')
    op.drop_table('perm_grants')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('issue_tags')
    op.drop_table('issue_links')
    op.drop_index(op.f('ix_hardware_assets_purchase_status'), table_name='hardware_assets')
    op.drop_index(op.f('ix_hardware_assets_project_id'), table_name='hardware_assets')
    op.drop_index(op.f('ix_hardware_assets_model_id'), table_name='hardware_assets')
    op.drop_index(op.f('ix_hardware_assets_location_id'), table_name='hardware_assets')
    op.drop_table('hardware_assets')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_comments_issue_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_blockers_issue_id'), table_name='blockers')
    op.drop_table('blockers')
    op.drop_index(op.f('ix_activity_log_issue_id'), table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index(op.f('ix_issues_status_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_sprint_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_project_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_assignee_user_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_sprints_board_id'), table_name='sprints')
    op.drop_table('sprints')
    op.drop_index(op.f('ix_job_runs_job_id'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_hardware_workflow_steps_workflow_id'), table_name='hardware_workflow_steps')
    op.drop_table('hardware_workflow_steps')
    op.drop_index(op.f('ix_board_columns_board_id'), table_name='board_columns')
    op.drop_table('board_columns')
    op.drop_index(op.f('ix_workflow_statuses_project_id'), table_name='workflow_statuses')
    op.drop_table('workflow_statuses')
    op.drop_table('webhook_subs')
    op.drop_index(op.f('ix_skills_key'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_permissions_project_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_messages_project_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_issue_types_project_id'), table_name='issue_types')
    op.drop_table('issue_types')
    op.drop_table('issue_counters')
    op.drop_table('hardware_workflows')
    op.drop_index(op.f('ix_boards_project_id'), table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_agent_definitions_user_id'), table_name='agent_definitions')
    op.drop_table('agent_definitions')
    op.drop_index(op.f('ix_user_secrets_user_id'), table_name='user_secrets')
    op.drop_table('user_secrets')
    op.drop_index(op.f('ix_saved_filters_owner_id'), table_name='saved_filters')
    op.drop_table('saved_filters')
    op.drop_index(op.f('ix_projects_parent_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_plugin_files_plugin_id'), table_name='plugin_files')
    op.drop_table('plugin_files')
    op.drop_index(op.f('ix_mcp_servers_user_id'), table_name='mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_index(op.f('ix_webhook_coalesce_route'), table_name='webhook_coalesce')
    op.drop_table('webhook_coalesce')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('provider_models')
    op.drop_table('plugins')
    op.drop_index(op.f('ix_locations_parent_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_table('hardware_models')
    # ### end Alembic commands ###
